Platzhalter hinzugefügt
ijug-ev/JavaLand pull request #25
Opened 2022-10-19 10:56 UTC by hendrikebbers

2022-10-19 10:58 UTC, hendrikebbers commented
@mkarg Der PR kann natürlich auch gerne erst gemergt werden, wenn der Text voll da ist. Gibt es eigentlich eine Deadline?

2022-10-22 13:55 UTC, mkarg commented
@hendrikebbers Eine Deadline gibt es nur indirekt: Was wir an Texten bis zum Redaktionsschluss haben, kann noch in Prospekt / Webseite beworben werden. Was später eingeht steht für diese Werbezwecke halt nicht zur Verfügung. Auf die Annahme / Ablehnung einer Einreichung hat das keine Auswirkung. Wenn wir wissen dass Ihr definitiv was veranstaltet, halten wir Euch defintiv Räume dafür frei -- Auch wenn Euch der Text dafür erst einen Tag vor der Konferenz einfällt. :-)

Ich setze Eueren PR erstmal auf Draft, bis Euch ein Text eingefallen ist, danach merge ich es gerne.

2022-11-16 11:27 UTC, hendrikebbers commented
@mkarg @TimRiemer hab den PR endlich fertig ausgefüllt ;)

2022-11-19 15:36 UTC, mkarg requested changes
Hendrik, leider muss ich den PR "aus technischen Gründen" ablehnen. Erstens, wir brauchen für jede Einreichung einen eigene PR, damit wir sie getrennt bewerten können. Zweitens, Du reichst CAs ein, die bereits eingereicht sind. Trenne es bitte auf und reiche nur Aktivitäten ein, die noch nicht eingereicht sind. Danke.

**Edit** War wohl ein technischer Fehler von Github oder Browser. Dein PR sieht gut aus! 👍

2022-11-19 16:03 UTC, mkarg approved these changes
Sieht gut aus

2022-11-19 16:04 UTC, mkarg commented
> Hendrik, leider muss ich den PR "aus technischen Gründen" ablehnen.

War wohl ein Fehler von Github, nach mehrmaligem Refresh habe ich endlich Deinen "wirklichen" Text gesehen. Oder mein Browser hat einen Cache-Fehler. Sorry, Hendrik, für die Verwirrung! 😅

2022-11-24 06:33 UTC, TimRiemer commented
👍 Danke Hendrik

2022-11-24 06:33 UTC, merged