Hacking the 2040
ijug-ev/JavaLand pull request #36
Opened 2022-11-08 10:56 UTC by rdmueller

neue Community-Aktivität, falls sich ein Sponsor findet

2022-11-19 16:14 UTC, mkarg commented on Community-Aktivitäten/README.md
> +*WICHTIG*: für die Hardware wird noch ein Sponsor benötigt - ohne wird es langweilig
Wir können Euere Idee leider erst veröffentlichen, wenn Ihr einen Sponsor gefunden habt. Wie ist da der Stand im Moment?

Bitte erweitert den Beschreibungstext noch um eine kurze Idee, was die Teilnehmer aktiv tun werden. Danke! :-)

2022-11-19 16:14 UTC, mkarg requested changes
Wir können Euere Idee leider erst veröffentlichen, wenn Ihr einen Sponsor gefunden habt. Wie ist da der Stand im Moment?

Bitte erweitert den Beschreibungstext noch um eine kurze Idee, was die Teilnehmer aktiv tun werden. Danke! :-)

2022-11-19 16:57 UTC, rdmueller commented
Das Sponsoring wird sich nächste Woche klären.

2022-11-19 17:07 UTC, rdmueller commented
Habe die Beispiele, was wir in solch einer Session machen können, erweitert:

* Umsetzung eines Video-Spiels
* Darstellung eines QR-Codes (JavaLand Eintritts-Code?)
* Grafikdemo

2022-11-24 07:15 UTC, mkarg commented
@rdmueller Gibt es Neuigkeiten von der Sponsorenfront, oder wollt Ihr evtl. das Event auch ohne Sponsor machen, aber die Teilnehmer müssen ihr eigenes Equipment bringen?

2022-11-24 09:42 UTC, rdmueller commented
Morgen Mittag weiss ich mehr.

2022-11-26 08:57 UTC, mkarg commented
"Morgen Mittag" ist vorbei, und nun?

2022-11-29 08:13 UTC, rdmueller commented
Sorry, die Entscheidung wurde Freitag getroffen, hat mich aber erst jetzt erreicht. Wir haben das Sponsoring! Ich ändere gerade noch den Text ab.

2022-11-29 08:15 UTC, rdmueller commented
so. geändert. ready to be merged

2022-11-29 18:33 UTC, mkarg approved these changes
@TimRiemer Vom meiner Seite OK, was meinst Du?

2022-11-30 07:47 UTC, TimRiemer commented
👍
Hab ich jetzt schon Lust drauf :)

2022-11-30 07:47 UTC, merged