JavaLand4Kidadults - Das große Rennen
ijug-ev/JavaLand pull request #51
Opened 2023-12-04 18:04 UTC by futzlig

Passend zum Veranstaltungsort sollten wir doch ein Rennen veranstalten, oder?

2023-12-05 07:44 UTC, mkarg requested changes
Vielen Dank für diese super Idee! Gerne können wir auch einen Parcour im Innenraum finden, sodass das ganze mit Publikum in interessanter Kulisse stattfinden kann.

Zur Aufnahme ist leider eine kleine Änderung notwendig: Jede CA benötigt exakt einen Verantwortlichen, der für uns als Ansprechpartner dient und der eine kostenlose Eintrittskarte erhält. Bitte markiert diesen in der Überschrift mit *sternchen*. Danke!

:+1:

2023-12-05 09:53 UTC, futzlig commented
Hallo @mkarg ,
freut mich, das euch der Vorschlag gefällt. Das mit dem Parcours im Innenraum hört sich sehr gut an. Ich denke, ich werde auch noch ein paar Preise für das oder die Gewinner-Teams organisieren.
Viele Grüße,
Fin

2023-12-05 12:21 UTC, mkarg commented
> Hallo @mkarg , freut mich, das euch der Vorschlag gefällt. Das mit dem Parcours im Innenraum hört sich sehr gut an. Ich denke, ich werde auch noch ein paar Preise für das oder die Gewinner-Teams organisieren.

Ich habe intern auch darum gebeten mal die JavaLand-Sponsoren nach Preisen zu fragen.

> Die "Sternchen" habe ich ergänzt.

Danke Dir!

2023-12-05 12:23 UTC, mkarg approved these changes

2023-12-19 09:14 UTC, mkarg commented
@futzlig Das JavaLand Back Office steht in Kontakt mit den JavaLand-Sponsoren und hilft gerne bei der Vermittlung von Preisen für die Gewinner. Dazu gibt es aber Rückfragen. Kannst Du Dich bitte dazu kurzfristig direkt mit [Carmen Al-Youssef](carmen.al-youssef@doag.org) in Verbindung setzen? Danke Dir! :-)

2023-12-19 09:14 UTC, mkarg commented
@futzlig Kannst Du bitte Deinen Branch auf den aktuellen master rebasen? Danke.

2023-12-19 17:37 UTC, futzlig commented
> @futzlig Das JavaLand Back Office steht in Kontakt mit den JavaLand-Sponsoren und hilft gerne bei der Vermittlung von Preisen für die Gewinner. Dazu gibt es aber Rückfragen. Kannst Du Dich bitte dazu kurzfristig direkt mit [Carmen Al-Youssef](carmen.al-youssef@doag.org) in Verbindung setzen? Danke Dir! :-)

Ja, mache ich.

2023-12-19 17:39 UTC, futzlig commented
/rebase

2024-01-16 09:58 UTC, quipsy-karg commented on Community-Aktivitäten/README.md
> +Am Montag- und Dienstagabend findet ihr euch zu Teams zusammen, baut und programmiert euren Wagen (Qualifying).
Wie lange baut Ihr an den Autos?

2024-01-19 15:16 UTC, futzlig commented on Community-Aktivitäten/README.md
> +Am Montag- und Dienstagabend findet ihr euch zu Teams zusammen, baut und programmiert euren Wagen (Qualifying).
Das kann ich dir nicht sagen, wie lange die Teilnehmer dafür brauchen werden. Vielleicht kann man an den beiden Abenden jeweils 1 Stunde irgendwo reservieren, damit sich die Teilnehmer ggf. austauschen (abgucken) können. Sonst müssen Sie auf ihrem Hotelzimmer oder wo auch immer weiterbauen.
Da ich die Lokation vor Ort nicht kenne und ich auch noch keine Erfahrung habe, wenn frei gebaut wird, ist das schwer, hier eine genaue Zeit zu sagen.

2024-02-04 16:19 UTC, TimRiemer commented
Thumbs up!

2024-02-04 16:19 UTC, merged